### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: ./ckpts/Qwen2.5-7B-Instruct
adapter_name_or_path: saves/qwen2.5-7b/cls
template: qwen
finetuning_type: lora
additional_target: head_cls

### export
export_dir: models/qwen2.5-7b/cls
export_size: 4
export_device: cpu
export_legacy_format: false

### custom
training_stage: 3
num_classes: 5
num_feature_nodes: 37
feature_subset: null
alignment_type: additive
x_dim: 1
z_dim: 1
graph_threshold: 0.3
tau_A: 0.0
lambda_A: 0.0
c_A: 1.0
encoder_hidden_size: 128
decoder_hidden_size: 128
h_tol: 0.00000001
gamma: 1.0
cls_lambda: 1.0
align_lambda: 1.0
elbo_lambda: 1.0
rec_lambda: 1.0
feature_name_path: ./prior_knowledge/feature_name_mapping.json
forbidden_edges_filepath: ./prior_knowledge/forbidden_edges.csv
positive_required_edges_filepath: ./prior_knowledge/positive_required_edges.csv
negative_required_edges_filepath: ./prior_knowledge/negative_required_edges.csv